### ISSUE TITLE
Error updating prices Prestashop 1.7.6.3

### ISSUE THREAD

**Issue by DavidMG83** [NKoonen/NewPriceList#1]
Hello, first of all, thanks for your contribution.

I have downloaded your php file and followed the steps in the guide.

Although the message is displayed as " Price Update Done!" , prices are not updated.

could you help me please?

Thanks in advance for your support.
![Captura](https://user-images.githubusercontent.com/60195655/74886869-9d188700-5379-11ea-8ba2-8509c3d97f1e.JPG)

**Comment by NKoonen** [comment]
Hi, could you share (a piece) of your csv file?
And what Prestashop version are you using?

**Comment by DavidMG83** [comment]
Thank you very much for your quick answer.

 

Please find attached mi CSV example.

 

Mi Prestashop versión is 1.7.6.3

 

I´m ussing Transformer Theme.

 

De: NKoonen <notifications@github.com> 
Enviado el: jueves, 20 de febrero de 2020 10:21
Para: NKoonen/NewPriceList <NewPriceList@noreply.github.com>
CC: DavidMG83 <info@asacua.com>; Author <author@noreply.github.com>
Asunto: Re: [NKoonen/NewPriceList] Error updating prices Prestashop 1.7.6.3 (#1)

 

Hi, could you share (a piece) of your csv file?
And what Prestashop version are you using?

**Comment by NKoonen** [comment]
Hi, i cant seem to find the attachment. DId you add in the attachment in [this](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) method?

**Comment by DavidMG83** [comment]
Hi,
I can´t attach CSV file.
Github say: "we don´t support that file type" Just support these files:

PNG (.png)
GIF (.gif)
JPEG (.jpg)
Log files (.log)
Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents
Text files (.txt)
PDFs (.pdf)
ZIP (.zip, .gz)

Can i send you a email?

**Comment by NKoonen** [comment]
Sure, send it to NewPriceList@inform-all.nl

**Comment by DavidMG83** [comment]
E-mail sent

**Comment by NKoonen** [comment]
Fixed.
Make sure the .csv file is comma separated.

**Comment by DavidMG83** [comment]
Thank you very much for your help!!
